title: Rick Nouwen  # Add a space after the period
description: Curriculum Vitae

logo: me23rounded.png # Use a relative path to logo image 

remote_theme: jekyll-theme-minimal

email: r.w.f.nouwen@uu.nl # Allow visitors to contact you
