title: Rick Nouwen  # Add a space after the period
description: Curriculum Vitae

logo: me23rounded.png # Use a relative path to logo image 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

email: r.w.f.nouwen@uu.nl # Allow visitors to contact you
